### ISSUE TITLE
Automatically label the horizontal/vertical plot axes

### ISSUE THREAD

**Issue by griffin28** [LLNL/PyDV#147]
From Matt O'Brien:

> Is there a way for PyDV to automatically label the horizontal and vertical axes of a plot by extracting the information from the curve label or we could add additional meta-data to the curve header to automate this. Basically I would like to have "presentation quality" plots with as little "human intervention" as possible.

**Comment by rusu24edward** [comment]
This can be done already via python scripting and if loading Sina files. I'm looking into paths forward for ultra files

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
