### ISSUE TITLE
normalize command

### ISSUE THREAD

**Issue by griffin28** [LLNL/PyDV#153]
Procedure: Construct a new curve with unit area in its domain.
Usage: normalize curve

**Comment by griffin28** [comment]
```
U-> span 1 20
U-> cos a
U-> grid off
U-> normalize a
```

![Screen Shot 2020-05-11 at 4 15 19 PM](https://user-images.githubusercontent.com/26772741/81621212-b3dfe000-93a2-11ea-896d-f7e9a1bf1d8d.png)

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
