### ISSUE TITLE
plot command

### ISSUE THREAD

**Issue by griffin28** [LLNL/PyDV#155]
Procedure: Turn plotting of curves to the screen on or off. Even when plotting is off the curves still exist and may be manipulated. The ‘-s’ execute line option causes ULTRA to start-up with plotting turned off. The ‘-u’ execute line option causes ULTRA to start-up with plotting turned on. This is the default.
Usage: plots on | off

Will help solve #154

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
