### ISSUE TITLE
Add axis command

### ISSUE THREAD

**Issue by griffin28** [LLNL/PyDV#157]
Command type: plot control command
Variable: Controls drawing the axes
Usage: axis on | off

**Comment by griffin28** [comment]
```
U-> axis on
```
![Screen Shot 2020-05-11 at 3 53 35 PM](https://user-images.githubusercontent.com/26772741/81620158-108dcb80-93a0-11ea-87a0-946bfbb9ad8c.png)

**Comment by griffin28** [comment]
```
U-> axis off
```
![Screen Shot 2020-05-11 at 3 52 55 PM](https://user-images.githubusercontent.com/26772741/81620189-213e4180-93a0-11ea-8558-5da936026111.png)

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
