### ISSUE TITLE
Add delta command

### ISSUE THREAD

**Issue by griffin28** [LLNL/PyDV#164]
Procedure: generate a Dirac delta distribution such that Int(xmin, xmax, dt*delta(t - x0)) = 1
     Usage: delta xmin x0 xmax [# points]

**Comment by griffin28** [comment]
```
U-> delta 0 5 20 100
```

![Screen Shot 2020-05-11 at 6 06 46 PM](https://user-images.githubusercontent.com/26772741/81627199-813de380-93b2-11ea-8a61-6818463002bb.png)

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
