### ISSUE TITLE
Add hypot command

### ISSUE THREAD

**Issue by griffin28** [LLNL/PyDV#167]
Procedure: Calculate harmonic average of two curves, `sqrt(a^2+b^2)`
     Usage: hypot **a b**

**Comment by griffin28** [comment]
```
U-> span 1 20
U-> span 1 20
U-> cos a
U-> sin b
U-> hypot a b
```

![Screen Shot 2020-05-12 at 8 55 09 AM](https://user-images.githubusercontent.com/26772741/81716803-aa9c5500-942e-11ea-93b3-91373ab2edc2.png)

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
