### ISSUE TITLE
Add theta command

### ISSUE THREAD

**Issue by griffin28** [LLNL/PyDV#169]
Procedure: generate a unit step distribution such that` d(theta(t - x0))/dt = delta(t - x0)`
     Usage: theta **xmin x0 xmax** [**# points**]

**Comment by griffin28** [comment]
```
U-> theta 5 10 20 200
```

![Screen Shot 2020-05-12 at 9 48 18 AM](https://user-images.githubusercontent.com/26772741/81722089-bfc8b200-9435-11ea-8e6d-c21badc91ca5.png)

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
