### ISSUE TITLE
import pydv turn on matplotlib DEBUG messages that cannot be turned off

### ISSUE THREAD

**Issue by doutriaux1** [LLNL/PyDV#170]
if I import pydv in my code, when running nosetest on my test suite I get loads of matplotlib debug messages that I cannot filter out.

For more details see:

https://github.com/matplotlib/matplotlib/issues/17397

**Comment by doutriaux1** [comment]
I'm using the version of pydv that is on LC at:
```
/usr/gapps/pydv/current
```

**Comment by griffin28** [comment]
@doutriaux1 I'm not seeing this on the PyDV end, however, there are User warnings that I wasn't suppressing that I've added filtering for: `warnings.filterwarnings("ignore", category=UserWarning)`

I believe this is a nose issue as mentioned by @tacaswell

**Comment by doutriaux1** [comment]
@griffin28 @tacaswell you are right switching to pytest makes this disappear. Thanks!
