### ISSUE TITLE
Add PyDV docs to closed side

### ISSUE THREAD

**Issue by griffin28** [LLNL/PyDV#187]
Hi Kevin,
 
Thanks for the new features. What do you think about making the PyDV Read the Docs documentation available on the SCF? Walt did this recently for PMESH, and C2C also has their documentation available as a webpage you can navigate to on the SCF.
 
-Eric

**Comment by rusu24edward** [comment]
Talking with Teresa Bailey. Depends on her response, but my initial thought: move the .html files to the gapps folder as part of the scf releases. Users can then launch firefox or some other browser to view them.

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
