### ISSUE TITLE
Using plot names in the cur command

### ISSUE THREAD

**Issue by griffin28** [LLNL/PyDV#188]
Using plot names in the ‘cur’ command. Many times I have plot names that are similar such as : temperature 1, temperature 2, temperature 3, etc. it would be useful to do a cur command like this: cur ^temp.* to plot all of my temperature curves without first finding the number of the plot using the ‘menu’ command. It is sometimes easier for me to remember plot names than the plot number because a file could have thousands of plots.

requested by: Chester Eng

**Comment by griffin28** [comment]
Also, just a tweak on the suggestion for the 'cur' command that I mentioned earlier. Sometimes I have curves in my file labeled: Temp 1 part A, Temp 2 part A, Temp 3 part A, Temp 1 part B, Temp 2 part B, Temp 3 part B, etc.

It would be nice to only plot Temps from part A only so maybe something like:
cur Temp.*A
would be great too.

Thanks again Kevin!

Chester

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
