### ISSUE TITLE
Add directory label option to curve labels

### ISSUE THREAD

**Issue by crkrenn** [LLNL/PyDV#196]
I often use `pydv` to compare the same variable from different simulations. By default, `ultra` includes the file path in its legend. 

Would you consider this for `pydv` as an option?

Current legend:
```
-red-    x vs time
-blue-   x vs time
-purple- x vs time
```
Proposed legend:
```
-red-    x vs time (run1)
-blue-   x vs time (run2)
-purple- x vs time (run3)
```

Or: Proposed legend:
```
-red-    x vs time (run1/xxxx.ult)
-blue-   x vs time (run2/xxxx.ult)
-purple- x vs time (run3/xxxx.ult)
```
Thanks!

-Chris

**Comment by griffin28** [comment]
@crkrenn ...the `labelfilenames` command will append the filename to the legend label. See `help labelfilenames` for more details.

**Comment by rusu24edward** [comment]
@crkrenn Does @griffin28's suggestion capture what you're proposing?
