### ISSUE TITLE
Associate plot attributes, such as labels, with curves

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/PyDV#197]
Encode plot attributes in the saved files so that PyDV can automatically load the plot attributes, such as title, xlabel, and ylabel, when you select the curve from the menu. Currently, the labels are not associated with any curve or plot but are simply displayed in the main window. 

Consider special case when plotting multiple curves with different labels on the same window. Maybe if there is disagreement on the labels, each label could have a list of curves that apply to it
 
Label 1 (A, C, G)    Label 2 (B, D, E)

**Comment by rusu24edward** [comment]
Try to extract the labels and title from the curve name itself. Be aware of the different types of curve-name conventions used by the different codes.
So far we know of:
`ylabel vs xlabel`
`ylable vs. xlabel`
`title (ylabel vs xlabel)`
`_ylabel_vs_xlabel` -> I'm trying to find out if the leading underscore is on purpose.

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
