### ISSUE TITLE
Enhance the documentation description of the commands

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/PyDV#213]
Most of the descriptions in the documentation are fairly sparse. For some commands, this is okay, but others leave out critical information. For example, in the geometry command, it is not clear what are the reference points for <xlocation> <ylocation>. Does <xlocation> <ylocation> refers to the dislocation of some point on the PyDV window relative to some point on the screen? -- yes, relative to the top left.

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
