### ISSUE TITLE
semicolon documentation wrong

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/PyDV#215]
The manual states “Note: In PyDV commands, spaces are used to delimit items on the input line. More precisely items on a command line are either space delimited, are preceded by a left parenthesis if the first item in a list, or terminated by a right parenthesis if the last item in a list. Semicolons may be used to stack multiple commands on a single interactive input line. In interactive mode, ranges of curve numbers or data-id’s may be indicated using colon notation. For example, a:f or 5:9 “ (Page 4).

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
