### ISSUE TITLE
image from command file does not save well

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/PyDV#227]
Using the `image` command in a command file does not save well.
Here's an example data file
```
# darkness
0 0
1 1
2 4
3 9
4 16
# lightness
0 5
1 4
2 2.5
3 2.1
4 2.0
```

and here's an example command file:
```
rd data_file
cur 1 2
image test_image png
```

Running with this:
```
pdv -i command_file
```
here's the result from having `image` in the command file:
![image1](https://user-images.githubusercontent.com/18565891/117183569-8ac31700-ad8c-11eb-96f7-11b453819fbe.png)

compared to the result using image from the pydv interactive terminal:
![image2](https://user-images.githubusercontent.com/18565891/117183632-9d3d5080-ad8c-11eb-85b3-0e40d616fa69.png)

**Comment by rusu24edward** [comment]
Matplotlib splits the renderer from the canvas drawer. The first result is not drawing to a canvas, only using the renderer. The second result has already drawn to the canvas and then performs the save. This could help explain the difference.

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
