### ISSUE TITLE
makeintensive and makeextensive extra 0 points in y column

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/PyDV#241]
The 'makeintensive' and 'makeextensive' functions were added a few years ago.  While they are implemented correctly, the dataset that is being produced for each has a major problem. Every second data point has a zero 'y' value, which should not be included in the dataset.  For datasets with a large number of points, the result is a solid-looking 'picket fence'.  It plots really nasty in the viewer.  My request is to simply remove every other point with a zero 'y' value.

Work-arounds: I 'save'd the dataset to a file, edited it to remove every other zero 'y' value, and then read it in and plotted it in PyDV.  Voila.  It now plots are a standard curve, and not a nasty-looking picket fence.

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
