### ISSUE TITLE
convolb inconsistent with ultra

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/PyDV#244]
Convolb in PyDV is inconsistent with Ultra.

```
gaussian 1 1 5
gaussian 1 0.1 0
convolb a b
```

PyDV:
![Screen Shot 2021-11-29 at 10 23 59 AM](https://user-images.githubusercontent.com/18565891/143922510-6778487e-6c6e-45c7-b568-2c39c07794ab.png)
Ultra:
![Screen Shot 2021-11-29 at 10 24 07 AM](https://user-images.githubusercontent.com/18565891/143922518-900364fb-8efa-4107-a1aa-10b53fdaad0e.png)

They should match up

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
