### ISSUE TITLE
consolidate linemarker and marker

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/PyDV#250]
[linemarker](https://pydv.readthedocs.io/en/latest/curve_control_cmds.html#linemarker) and [marker](https://pydv.readthedocs.io/en/latest/plot_control_cmds.html?highlight=marker#marker) seem to do the same thing, although marker doesn't seem to work. Consolidate them into a single function, probably `linemarker` with shortcut `marker`.

**Comment by rusu24edward** [comment]
There are some other functions like this, we should include them in this effort.

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
