### ISSUE TITLE
add curve list support to these commands

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/PyDV#253]
Some commands that ought to work with curve lists:
[`label <curve-list> [<new-labels>]`](https://pydv.readthedocs.io/en/latest/plot_control_cmds.html#label)
[getattributes](https://pydv.readthedocs.io/en/latest/curve_inquiry_cmds.html#getattributes)
[getlabel](https://pydv.readthedocs.io/en/latest/curve_inquiry_cmds.html#getlabel)
[getnumpoints](https://pydv.readthedocs.io/en/latest/curve_inquiry_cmds.html#getnumpoints)
[getymin](https://pydv.readthedocs.io/en/latest/curve_inquiry_cmds.html#getymin-2-4-2)
[getymax](https://pydv.readthedocs.io/en/latest/curve_inquiry_cmds.html#getymax-2-4-2)

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
