### ISSUE TITLE
geometry in script

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/PyDV#255]
Running the following from the command line:
```
rd testData.txt
cur 1
geometry 500 500 0 0
image myPlot_script.jpg
quit
```
gives a nice image like this:
![Screen Shot 2021-12-14 at 9 54 34 AM](https://user-images.githubusercontent.com/18565891/146053274-b9868660-b18a-4b2b-bdb6-f09ffab57f59.png)

However, save it as a script and run it with `pdv -i script` gives a terrible image:
![Screen Shot 2021-12-14 at 9 54 59 AM](https://user-images.githubusercontent.com/18565891/146053346-24839e52-82f4-4abb-af46-5ec80f88c0f3.png)

The images should be the same.

Note: this will change all baseline images in the test.

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
