### ISSUE TITLE
New ultra file reader issues

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/PyDV#272]
Some ultra files have tabs between the numbers, and this is not splitting correctly.

Also, some users have the curve name starting with `#` and they do not have a space after it, e.g.:
```
#my_curve
x y
x y
...
```
This will fail too

We also need to see what PyDV produces when writing a file. Users report that files are written with no space in between the comment sign and the curve name. This needs to be consistent.

These errors also exist using the csv option.

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
