### ISSUE TITLE
Import of "curve" in module should be relative to module

### ISSUE THREAD

**Issue by vsoch** [LLNL/PyDV#275]
Hiya! In this line here:

https://github.com/LLNL/PyDV/blob/0a09ed393dfc258ff9db3865ca30ce1f9f0974df/pydv/pydvpy.py#L97

I'm assuming you are referring to the local file "curve.py"

https://github.com/LLNL/PyDV/blob/master/pydv/curve.py

This won't work in different contexts, for example just now I am trying to render a notebook that uses this library (and it cannot find curve because the import is not specific)

```bash
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[7], line 2
      1 # Note: pydv's big! Importing it may take a moment.
----> 2 from pydv import pydvpy as pydv
      3 import io
      4 import json

File /usr/local/lib/python3.8/dist-packages/pydv/pydvpy.py:97
     94 except:
     95     stylesLoaded = False
---> 97 import curve
     99 try:
    100     import pact.pdb as pdb

ModuleNotFoundError: No module named 'curve'
ModuleNotFoundError: No module named 'curve'
```
if possible, could this be changed to 

```python
import pydv.curve as curve
```

I can confirm this fixes this particular issue for me. Thank you!

**Comment by jmoreno45** [comment]
Updated/Fix in latest release.
