### ISSUE TITLE
`create_plot` returns the `plt` module (instead of a handle to the plot)

### ISSUE THREAD

**Issue by tomstitt** [LLNL/PyDV#277]
I'm not sure if this is intended but `create_plot` [returns `matplotlib.pyplot` (`plt`)](https://github.com/LLNL/PyDV/blob/master/pydv/pydvpy.py#L329) instead of a plot-specific reference like [`figure`](https://github.com/LLNL/PyDV/blob/master/pydv/pydvpy.py#L317) or [`axis`](https://github.com/LLNL/PyDV/blob/master/pydv/pydvpy.py#L252), does it make sense to return those instead? I currently just `matplotlib.pyplot.gcf()` after calling `create_plot` to interact with the reference but that is less ergonomic imo.

**Comment by doutriaux1** [comment]
@tomstitt this is a good idea. Thx for the feedback. Please keep it coming.

**Comment by jmoreno45** [comment]
Updated/Fixed in latest release.
