### ISSUE TITLE
Move to LLNL GitHub organization

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/PyDV#35]
I think it might be good to move this repo to [LLNL organization](https://github.com/LLNL).

**Comment by griffin28** [comment]
@markcmiller86 yeah, I think that's a good idea.

**Comment by griffin28** [comment]
Follow these instructions: https://software.llnl.gov/about/using-github/

**Comment by griffin28** [comment]
Transferred ownership to LLNL on 2/7/2020!
